# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-AAStar

wandb:
  log: false
  project: setattn-formal-parity
  run_name: null
model:
  pos_enc_type: learned
optim:
  epochs: 2000
data:
  dataset: Counter-3
  block_size: 1024
  # for dataloader
  mode: train
  lang: Counter
  num_par: 3 # number of character, 2 means 'anbn' 3 means 'anbncn'
  lower_window: 1
  upper_window: 150  # modified to suit increased len_incr, attention: need ablation for 16 layers!
  training_size: 50
  validation_size: 50
  test_size: 50
  len_incr: 50
  num_bins: 2
  debug: false
  loss_type: mse

