# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-AAStar

wandb:
  log: false
  project: setattn-formal-parity
  run_name: null

data:
  dataset: Counter-anbn
  block_size: 1024
  # for dataloader
  mode: train
  lang: Counter
  num_par: 2 # number of character, 2 means 'anbn' 3 means 'anbncn'
  lower_window: 1
  upper_window: 50
  training_size: 50
  test_size: 50
  len_incr: 50
  num_bins: 3
  debug: false
  loss_type: mse

