# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-AAStar

model:
  pos_enc_type: 'nope'
wandb:
  log: false
  project: setattn-formal-parity
  run_name: null
optim:
  epochs: 10000
data:
  dataset: AAStar
  block_size: 1024
  # for dataloader
  mode: train
  lang: AAStar
  num_par: 2 # number of 'a', 2 means 'aa'
  lower_window: 2
  upper_window: 500
  training_size: 150
  validation_size: 50
  test_size: 50
  len_incr: 100
  num_bins: 2
  debug: false
  loss_type: mse

