# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-AAStar

wandb:
  log: false
  project: setattn-formal-parity
  run_name: null

data:
  dataset: ABABStar
  block_size: 1024
  # for dataloader
  mode: train
  lang: ABABStar
  num_par: 2 # number of 'a', 2 means 'aa'
  lower_window: 4
  upper_window: 500
  training_size: 125
  validation_size: 25
  test_size: 25
  len_incr: 100
  num_bins: 2
  debug: false
  loss_type: mse

