# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-parity

wandb:
  log: false
  project: setattn-formal-parity
  run_name: null

data:
  dataset: Parity
  # for dataloader
  mode: train
  p_val: 0.5
  q_val: 0.5
  lang: Parity
  num_par: null
  lower_window: 2
  upper_window: 50
  training_size: 10000
  validation_size: 2000
  test_size: 2000
  len_incr: 50
  num_bins: 2
  debug: false
  loss_type: mse


