# conf/setattn.yaml
defaults:
  - setattn_formal

out_dir: out-formal-parity

wandb:
  log: false
  project: setattn-formal-parity
  run_name: null

data:
  dataset: Boolean-5
  # for dataloader
  mode: train
  p_val: 0.4 # 0.5->0.4 modified for faster genenration
  q_val: 0.25
  lang: Boolean
  num_par: 5
  lower_window: 2
  upper_window: 50
  lower_depth: 0
  upper_depth: -1
  bin1_lower_depth: 0
  bin1_upper_depth: -1
  training_size: 10000
  test_size: 2000
  len_incr: 50
  num_bins: 2
  debug: false
  loss_type: mse
  vary_depth: false

